### ISSUE TITLE
ACCESS TOKEN visible when ssh to container

### ISSUE THREAD

**Issue by ld-singh** [1Password/kubernetes-secrets-injector#41]
### Summary

When you ssh to your pod and run "env" you cannot see the secrets as just path of secrets like op://my-vault/item/username
This is great. But at the same time ACCESS TOKEN is visible as env variable which is a deal breaker. It is like handing over keys to all your secrets. Can this be fixed to hide the ACCESS TOKEN as well?

### Use cases

This will help in securing the secrets properly as secrets are hidden but access token to access those secrets is visible

### Proposed solution

Add this secret to connect server instead So that we do not need add this secret in every namespace and in every deloyment manifest.

### Is there a workaround to accomplish this today?

No workaround
### References & Prior Work

* 
*

**Comment by ld-singh** [comment]
Hey 1password team @volodymyrZotov @edif2008 
Do you any comments on this?
Thanks

**Comment by volodymyrZotov** [comment]
Hi @ld-singh . 
I assume you put `OP_CONNECT_TOKEN` or `OP_SERVICE_ACCOUNT_TOKEN` into Kubernetes Secret and use it in your manifest, aka
```
- name: OP_CONNECT_TOKEN
   valueFrom:
       secretKeyRef:
           name: onepassword-token
           key: token
```
And unfortunately, this is how [the Kubernetes Secrets work](https://kubernetes.io/docs/concepts/configuration/secret/#:~:text=Caution%3A,anyone%20with%20access%20to%20etcd.). After connecting to the pod you can check the env variables values. There is nothing the injector can do with that currently.

Try to follow the steps to secure your Kubernetes Secrets that are listed withing the link I provided above.

**Comment by ld-singh** [comment]
Thanks @volodymyrZotov 
Thats the very reason I am looking for solutions like 1Password secret injector. So i will probably have to find a workaround to inject this token. I assume this is used by op cli to fetch secrets.

**Comment by ld-singh** [comment]
@volodymyrZotov 
I have come up with a solution to problem I mentioned.
The solution is to add annotations to application deployment manifest .
Then create a secret for secret injector webhook with that token and make it available as env variable to webhook.
Now webhook will pass token to application based on value in annotation.
The token is now not visible in logs or as env in applications. Also since webhook is missing shell, helps from leaking there as well.
Now you only need to create 1 secret with all tokens and pass to webhook as env. there is no need to create secrets in every namespace.

I have working solution in my fork. I have tested and works really well
Could you please go through this and let me know if are happy to merge? currently I do not have permissions to create PR. 

My fork: https://github.com/ld-singh/kubernetes-secrets-injector

I have tested and works for me. I think it will make 1password secret injector more secure. Please do have a look.
Thanks
