### ISSUE TITLE
The namespace comes empty on `set-namespace` makefile

### ISSUE THREAD

**Issue by hiteshjoshi** [1Password/kubernetes-secrets-injector#44]
https://github.com/1Password/kubernetes-secrets-injector/blob/77d101e15325d9d8894657c6096b76378933de02/Makefile#L59C55-L59C109

On `make deploy` I get the following error.

```
Error: must specify exactly one namespace value
Usage:
  kustomize edit set namespace [flags]
```

I checked for namespace and the command `kubectl config view --minify -o jsonpath={..namespace}` is returning empty.

**Comment by timvahlbrock** [comment]
+1

**Comment by hiteshjoshi** [comment]
I think sometimes the default doesnt get setup. Anyway moved from 1password for k8. Doppler is better alternative.
